project_name: buffalo
release:
  github:
    owner: gobuffalo
    name: buffalo
  name_template: '{{.Tag}}'
brew:
  name: buffalo
  github:
    owner: gobuffalo
    name: homebrew-buffalo
  url_template: 'https://github.com/gobuffalo/buffalo/releases/download/v{{ .Version }}/{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage: https://gobuffalo.io
  description: A Go web development eco-system, designed to make your life easier.
  install: |
    bin.install "buffalo-no-sqlite"
    mv "#{bin}/buffalo-no-sqlite", "#{bin}/buffalo"
  test: |
    system "#{bin}/buffalo", "version"
builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
    main: ./buffalo/main.go
    binary: buffalo-no-sqlite
    hooks:
      pre: packr
      post: packr clean
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
    main: ./buffalo/main.go
    binary: buffalo-with-zbuffalo
    flags: -tags zbuffalo
    hooks:
      pre: packr
      post: packr clean
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
fpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
