FROM gobuffalo/buffalo:latest

ARG CODECOV_TOKEN
ARG CI
ARG TRAVIS
ARG TRAVIS_BRANCH
ARG TRAVIS_COMMIT
ARG TRAVIS_JOB_ID
ARG TRAVIS_JOB_NUMBER
ARG TRAVIS_OS_NAME
ARG TRAVIS_PULL_REQUEST
ARG TRAVIS_PULL_REQUEST_SHA
ARG TRAVIS_REPO_SLUG
ARG TRAVIS_TAG

ENV BP=$GOPATH/src/github.com/gobuffalo/buffalo
RUN rm -rf $BP
RUN mkdir -p $BP
WORKDIR $BP

COPY . .
RUN bash ./it.sh
