# This is a multi-stage Dockerfile and requires >= Docker 17.05
# https://docs.docker.com/engine/userguide/eng-image/multistage-build/
FROM gobuffalo/buffalo:{{.version}} as builder

RUN mkdir -p $GOPATH/src/{{.packagePath}}
WORKDIR $GOPATH/src/{{.packagePath}}

{{if .withWebpack -}}
# this will cache the npm install step, unless package.json changes
ADD package.json .
{{if .withYarn -}}
ADD yarn.lock .
RUN yarn install --no-progress
{{else -}}
RUN npm install --no-progress
{{end -}}
{{end -}}

ADD . .
{{if .withDep -}}
RUN dep ensure
{{else -}}
RUN go get $(go list ./... | grep -v /vendor/)
{{end -}}
RUN buffalo build --static -o /bin/app

FROM alpine
RUN apk add --no-cache bash
RUN apk add --no-cache ca-certificates

# Comment out to run the binary in "production" mode:
# ENV GO_ENV=production

WORKDIR /bin/

COPY --from=builder /bin/app .

EXPOSE 3000

# Comment out to run the migrations before running the binary:
# CMD /bin/app migrate; /bin/app
CMD /bin/app
