// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package vcs

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../vcs/templates", "ignore.tmpl", "\"dmVuZG9yLwoqKi8qLmxvZwoqKi8qLnNxbGl0ZQouaWRlYS8KYmluLwp0bXAvCm5vZGVfbW9kdWxlcy8KLnNhc3MtY2FjaGUvCiotcGFja3IuZ28KcHVibGljL2Fzc2V0cy8KLnZzY29kZS8KLmdyaWZ0ZXIvCi5lbnYKKiovLkRTX1N0b3JlCioucGlkCmNvdmVyYWdlCmNvdmVyYWdlLmRhdGEKLnN2bgouY29uc29sZV9oaXN0b3J5Ci5zYXNzLWNhY2hlLyoKLmpody1jYWNoZS8Kamh3LioKKi5zdWJsaW1lKgpub2RlX21vZHVsZXMvCmRpc3QvCmdlbmVyYXRlZC8KLnZlbmRvci8KCg==\"")
}
