package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/markbates/coke/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Gadget)
// DB Table: Plural (gadgets)
// Resource: Plural (Widgets)
// Path: Plural (/widgets)
// View Template Folder: Plural (/templates/widgets/)

// WidgetsResource is the resource for the Gadget model
type WidgetsResource struct {
	buffalo.Resource
}

// List gets all Gadgets. This function is mapped to the path
// GET /widgets
func (v WidgetsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	gadgets := &models.Gadgets{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Gadgets from the DB
	if err := q.All(gadgets); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	// hint for Auto renderer to search proper template location
	c.Set("template_prefix", "widgets")
	return c.Render(200, r.Auto(c, gadgets))
}

// Show gets the data for one Gadget. This function is mapped to
// the path GET /widgets/{widget_id}
func (v WidgetsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Gadget
	gadget := &models.Gadget{}

	// To find the Gadget the parameter widget_id is used.
	if err := tx.Find(gadget, c.Param("widget_id")); err != nil {
		return c.Error(404, err)
	}

	// hint for Auto renderer to search proper template location
	c.Set("template_prefix", "widgets")
	return c.Render(200, r.Auto(c, gadget))
}

// New renders the form for creating a new Gadget.
// This function is mapped to the path GET /widgets/new
func (v WidgetsResource) New(c buffalo.Context) error {
	// hint for Auto renderer to search proper template location
	c.Set("template_prefix", "widgets")
	return c.Render(200, r.Auto(c, &models.Gadget{}))
}

// Create adds a Gadget to the DB. This function is mapped to the
// path POST /widgets
func (v WidgetsResource) Create(c buffalo.Context) error {
	// Allocate an empty Gadget
	gadget := &models.Gadget{}

	// Bind gadget to the html form elements
	if err := c.Bind(gadget); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(gadget)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, gadget))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "gadget.created.success"))
	// and redirect to the widgets index page
	return c.Render(201, r.Auto(c, gadget))
}

// Edit renders a edit form for a Gadget. This function is
// mapped to the path GET /widgets/{widget_id}/edit
func (v WidgetsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Gadget
	gadget := &models.Gadget{}

	if err := tx.Find(gadget, c.Param("widget_id")); err != nil {
		return c.Error(404, err)
	}

	// hint for Auto renderer to search proper template location
	c.Set("template_prefix", "widgets")
	return c.Render(200, r.Auto(c, gadget))
}

// Update changes a Gadget in the DB. This function is mapped to
// the path PUT /widgets/{widget_id}
func (v WidgetsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Gadget
	gadget := &models.Gadget{}

	if err := tx.Find(gadget, c.Param("widget_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Gadget to the html form elements
	if err := c.Bind(gadget); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(gadget)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, gadget))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "gadget.updated.success"))
	// and redirect to the widgets index page
	return c.Render(200, r.Auto(c, gadget))
}

// Destroy deletes a Gadget from the DB. This function is mapped
// to the path DELETE /widgets/{widget_id}
func (v WidgetsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Gadget
	gadget := &models.Gadget{}

	// To find the Gadget the parameter widget_id is used.
	if err := tx.Find(gadget, c.Param("widget_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(gadget); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "gadget.destroyed.success"))
	// Redirect to the widgets index page
	return c.Render(200, r.Auto(c, gadget))
}
