// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package refresh

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../refresh/templates", "dot-buffalo.dev.yml.tmpl", "\"YXBwX3Jvb3Q6IC4KaWdub3JlZF9mb2xkZXJzOgotIHZlbmRvcgotIGxvZwotIGxvZ3MKLSBhc3NldHMKLSBwdWJsaWMKLSBncmlmdHMKLSB0bXAKLSBiaW4KLSBub2RlX21vZHVsZXMKLSAuc2Fzcy1jYWNoZQppbmNsdWRlZF9leHRlbnNpb25zOgotIC5nbwotIC5lbnYKYnVpbGRfcGF0aDogdG1wCmJ1aWxkX2RlbGF5OiAyMDBucwpiaW5hcnlfbmFtZToge3submFtZX19LWJ1aWxkCmNvbW1hbmRfZmxhZ3M6IFtdCmVuYWJsZV9jb2xvcnM6IHRydWUKbG9nX25hbWU6IGJ1ZmZhbG8K\"")
}
