app_root: .
ignored_folders:
- vendor
- log
- logs
- assets
- public
- grifts
- tmp
- node_modules
- .sass-cache
included_extensions:
- .go
- .html
- .md
- .js
- .tmpl
build_path: /tmp
build_delay: 200ns
binary_name: test_app-build
command_flags: []
enable_colors: true
log_name: buffalo
