name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      -
        name: Checkout Code
        uses: actions/checkout@master
      -
        name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
